# Generated by Django 4.1.5 on 2023-05-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('booklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(related_name='booklists', to='books.book'),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
