# Generated by Django 4.2 on 2023-05-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0002_alter_booklist_books_alter_booklist_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='books',
        ),
    ]
