# Generated by Django 4.2 on 2023-05-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklists', '0003_remove_booklist_books'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booklists',
            field=models.ManyToManyField(blank=True, related_name='books', to='booklists.booklist'),
        ),
    ]
